# Generated by Django 2.2.3 on 2020-03-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20200315_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='test_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='test картинка'),
        ),
    ]
