# Generated by Django 2.2.3 on 2020-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemon_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='test_time',
            field=models.DateTimeField(default=None, verbose_name='test время'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='test_time1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='время появления'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='test_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='test картинка'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='наименование на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='наименование на японском'),
            preserve_default=False,
        ),
    ]
