# Generated by Django 2.2.3 on 2020-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_pokemon_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='test_time1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время появления'),
        ),
    ]
