# Generated by Django 2.2.3 on 2020-03-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20200321_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='test_image',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='test_time',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='test_time1',
        ),
    ]
